[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

# settings required for EOF
via_ir = true
evm_version = "prague"
eof_version = 1
solc = "./eof-solc"

[fuzz]
runs = 5000
max_test_rejects = 150000
